### ISSUE TITLE
TemplateSyntaxError at /changepassword/

### ISSUE THREAD

**Issue by shanepinnell** [salopensource/sal#102]
TemplateSyntaxError at /changepassword/
'future' is not a registered tag library

Currently running 3.0.2.839. First noticed in 2.8 or 2.9 (not sure), upgraded to 3.0.1 per recommendation in Slack which didn't remedy the error. Just upgraded to 3.0.2.839 which presents the error.

http://dpaste.com/11W7TYJ

**Comment by shanepinnell** [comment]
Looks like this is a duplicate of 85? https://github.com/salopensource/sal/issues/85

**Comment by grahamgilbert** [comment]
You're right, I'm dumb
