### ISSUE TITLE
Allow static files from CDN

### ISSUE THREAD

**Issue by waderobson** [salopensource/sal#110]
There seems to be an issue hosting static files from a CDN. I started using a different storage driver for my static files like [here](https://www.caktusgroup.com/blog/2014/11/10/Using-Amazon-S3-to-store-your-Django-sites-static-and-media-files/). Some of Sal's templates are hard coded to use `/static/` so the static files are not loading from the CDN.

Changing the templates from something like:
```
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
```
to something like:
```
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
```
allows us to set the `STATIC_URL` to whatever we want in the settings. 
If this seems like a reasonable change, I can submit a PR with the changes.

Thanks

**Comment by grahamgilbert** [comment]
Yep, sounds fine.
