### ISSUE TITLE
NoReverseMatch at /licenses/new/

### ISSUE THREAD

**Issue by jsummers1994** [salopensource/sal#117]
All aspects of Sal are working except the licenses section keep getting the following error message?

NoReverseMatch at /licenses/new/
Reverse for 'index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Request Method:
GET 

Request URL:
http://odms05.aspire.don.ac.uk:8008/licenses/new/ 

Django Version:
1.10 

Exception Type:
NoReverseMatch 

Exception Value:
Reverse for 'index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
 

Exception Location:
/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py in _reverse_with_prefix, line 389 

Python Executable:
/usr/bin/python 

Python Version:
2.7.6 

Python Path:
['/home/docker/sal',
 '/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg',
 '/home/docker/sal',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages']
 

Server time:
Fri, 31 Mar 2017 12:43:26 +0100 

Traceback  Switch to copy-and-paste view 

/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py in inner 

39.            response = get_response(request)
 ...

▶ Local vars 

 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _legacy_get_response 

249.            response = self._get_response(request)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _get_response 

187.                response = self.process_exception_by_middleware(e, request)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py in _get_response 

185.                response = wrapped_callback(request, *callback_args, **callback_kwargs)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py in _wrapped_view 

23.                return view_func(request, *args, **kwargs)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 
 
 

/home/docker/sal/licenses/views.py in new_license 

48.    return render(request, 'forms/new_license.html', c)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/shortcuts.py in render 

30.    content = loader.render_to_string(template_name, context, request, using=using)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/loader.py in render_to_string 

68.    return template.render(context, request)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/backends/django.py in render 

66.            return self.template.render(context)
 ...

▶ Local vars 

 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in render 

208.                    return self._render(context)
 ...

▶ Local vars 

 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in _render 

199.        return self.nodelist.render(context)
 ...

▶ Local vars 

 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in render 

994.                bit = node.render_annotated(context)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in render_annotated 

961.            return self.render(context)
 ...

▶ Local vars 

 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py in render 

174.        return compiled_parent._render(context)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in _render 

199.        return self.nodelist.render(context)
 ...

▶ Local vars 

 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in render 

994.                bit = node.render_annotated(context)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in render_annotated 

961.            return self.render(context)
 ...

▶ Local vars 

 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/loader_tags.py in render 

70.                result = block.nodelist.render(context)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in render 

994.                bit = node.render_annotated(context)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/base.py in render_annotated 

961.            return self.render(context)
 ...

▶ Local vars 

 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/template/defaulttags.py in render 

447.            url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/urls/base.py in reverse 

91.    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py in _reverse_with_prefix 

389.            (lookup_view_s, args, kwargs, len(patterns), patterns)
 ...

▶ Local vars 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

Request information

USER

administrator

GET

No GET data

POST

No POST data

FILES

No FILES data

COOKIES

Variable

Value

csrftoken 'BPVU1sUYp6w4XJv5r3hBxTCioA6E35PiyzzXinZwbQf103Lw0EOmbaSBi9EbTcXv'
 
_session_id 'e6d8cdb280cbd5328b5ed66f2c8f038a'
 
csrf_token 'uiDSc3ji7CuI29uZjHBdoYmiFk45Vnf0EBiNOv45eKw%3D'
 
_ga 'GA1.3.1999153829.1476699951'
 
sessionid 'jp9nv2hjw35nuuvn7rzawp3cyx6gl5zg'
 

META

Variable

Value

ADMIN_PASS 'pass'
 
APPNAME 'Sal'
 
APP_DIR '/home/docker/sal'
 
CONTENT_LENGTH ''
 
CONTENT_TYPE 'text/plain'
 
CSRF_COOKIE 'BPVU1sUYp6w4XJv5r3hBxTCioA6E35PiyzzXinZwbQf103Lw0EOmbaSBi9EbTcXv'
 
DB_ENV_DB_NAME 'sal'
 
DB_ENV_DB_PASS 'password'
 
DB_ENV_DB_USER 'admin'
 
DB_ENV_LANG 'en_US.utf8'
 
DB_ENV_PGDATA '/var/lib/postgresql/data'
 
DB_ENV_PG_MAJOR '9.4'
 
DB_ENV_PG_VERSION '9.4.5-2.pgdg80+1'
 
DB_ENV_no_proxy '*.local, 169.254/16'
 
DB_NAME 'sal'
 
DB_PASS 'password'
 
DB_PORT 'tcp://172.17.0.3:5432'
 
DB_PORT_5432_TCP 'tcp://172.17.0.3:5432'
 
DB_PORT_5432_TCP_ADDR '172.17.0.3'
 
DB_PORT_5432_TCP_PORT '5432'
 
DB_PORT_5432_TCP_PROTO 'tcp'
 
DB_USER 'admin'
 
DEBIAN_FRONTEND 'noninteractive'
 
DJANGO_SETTINGS_MODULE 'sal.settings'
 
DOCKER_SAL_ADMINS 'Docker User, docker@localhost'
 
DOCKER_SAL_DEBUG 'true'
 
DOCKER_SAL_DISPLAY_NAME 'Sal'
 
DOCKER_SAL_LANG 'en_GB'
 
DOCKER_SAL_TZ 'Europe/London'
 
GATEWAY_INTERFACE 'CGI/1.1'
 
HOME '/root'
 
HOSTNAME '95501d061fe0'
 
HTTP_ACCEPT 'text/html, application/xhtml+xml, */*'
 
HTTP_ACCEPT_ENCODING 'gzip, deflate'
 
HTTP_ACCEPT_LANGUAGE 'en-GB'
 
HTTP_CONNECTION 'Keep-Alive'
 
HTTP_COOKIE '_ga=GA1.3.1999153829.1476699951; csrf_token=uiDSc3ji7CuI29uZjHBdoYmiFk45Vnf0EBiNOv45eKw%3D; _session_id=e6d8cdb280cbd5328b5ed66f2c8f038a; csrftoken=BPVU1sUYp6w4XJv5r3hBxTCioA6E35PiyzzXinZwbQf103Lw0EOmbaSBi9EbTcXv; sessionid=jp9nv2hjw35nuuvn7rzawp3cyx6gl5zg'
 
HTTP_DNT '1'
 
HTTP_HOST 'odms05.aspire.don.ac.uk:8008'
 
HTTP_MAX_FORWARDS '10'
 
HTTP_REFERER 'http://odms05.aspire.don.ac.uk:8008/licenses/'
 
HTTP_USER_AGENT 'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko'
 
HTTP_VIA '1.1 proxy.don.ac.uk:8080'
 
OLDPWD '/home/docker/sal'
 
PATH '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
 
PATH_INFO u'/licenses/new/'
 
PWD '/home/docker/sal'
 
PYTHONPATH ':/home/docker/sal'
 
QUERY_STRING ''
 
REMOTE_ADDR '172.17.0.1'
 
REMOTE_HOST ''
 
REQUEST_METHOD 'GET'
 
RUN_MAIN 'true'
 
SCRIPT_NAME u''
 
SERVER_NAME '95501d061fe0'
 
SERVER_PORT '8000'
 
SERVER_PROTOCOL 'HTTP/1.1'
 
SERVER_SOFTWARE 'WSGIServer/0.1 Python/2.7.6'
 
SHLVL '1'
 
TZ 'Europe/London'
 
_ '/usr/bin/python'
 
no_proxy '*.local, 169.254/16'
 
wsgi.errors <open file '<stderr>', mode 'w' at 0x7fb0d07f31e0>
 
wsgi.file_wrapper ''
 
wsgi.input <socket._fileobject object at 0x7fb0c01e4cd0>
 
wsgi.multiprocess False
 
wsgi.multithread True
 
wsgi.run_once False
 
wsgi.url_scheme 'http'
 
wsgi.version (1, 0)
 

Settings

Using settings module sal.settings

Setting

Value

ABSOLUTE_URL_OVERRIDES {}
 
ADD_TO_ALL_BUSINESS_UNITS False
 
ADMINS (('Docker User', ' docker@localhost'),)
 
ALLOWED_HOSTS ['*']
 
APPEND_SLASH True
 
AUTHENTICATION_BACKENDS [u'django.contrib.auth.backends.ModelBackend']
 
AUTH_PASSWORD_VALIDATORS u'********************'
 
AUTH_PROFILE_MODULE 'sal.UserProfile'
 
AUTH_USER_MODEL u'auth.User'
 
BASIC_AUTH True
 
BOOTSTRAP3 {'set_placeholder': False}
 
CACHES {u'default': {u'BACKEND': u'django.core.cache.backends.locmem.LocMemCache'}}
 
CACHE_MIDDLEWARE_ALIAS u'default'
 
CACHE_MIDDLEWARE_KEY_PREFIX u'********************'
 
CACHE_MIDDLEWARE_SECONDS 600
 
CRYPT_URL None
 
CSRF_COOKIE_AGE 31449600
 
CSRF_COOKIE_DOMAIN None
 
CSRF_COOKIE_HTTPONLY False
 
CSRF_COOKIE_NAME u'csrftoken'
 
CSRF_COOKIE_PATH u'/'
 
CSRF_COOKIE_SECURE False
 
CSRF_FAILURE_VIEW u'django.views.csrf.csrf_failure'
 
CSRF_HEADER_NAME u'HTTP_X_CSRFTOKEN'
 
CSRF_TRUSTED_ORIGINS []
 
DATABASES {'default': {'ATOMIC_REQUESTS': False,
             'AUTOCOMMIT': True,
             'CONN_MAX_AGE': 0,
             'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'HOST': '172.17.0.3',
             'NAME': 'sal',
             'OPTIONS': {},
             'PASSWORD': u'********************',
             'PORT': '5432',
             'TEST': {'CHARSET': None,
                      'COLLATION': None,
                      'MIRROR': None,
                      'NAME': None},
             'TIME_ZONE': None,
             'USER': 'admin'}}
 
DATABASE_ROUTERS []
 
DATA_UPLOAD_MAX_MEMORY_SIZE 2621440
 
DATA_UPLOAD_MAX_NUMBER_FIELDS 1000
 
DATETIME_FORMAT u'N j, Y, P'
 
DATETIME_INPUT_FORMATS [u'%Y-%m-%d %H:%M:%S',
 u'%Y-%m-%d %H:%M:%S.%f',
 u'%Y-%m-%d %H:%M',
 u'%Y-%m-%d',
 u'%m/%d/%Y %H:%M:%S',
 u'%m/%d/%Y %H:%M:%S.%f',
 u'%m/%d/%Y %H:%M',
 u'%m/%d/%Y',
 u'%m/%d/%y %H:%M:%S',
 u'%m/%d/%y %H:%M:%S.%f',
 u'%m/%d/%y %H:%M',
 u'%m/%d/%y']
 
DATE_FORMAT u'N j, Y'
 
DATE_INPUT_FORMATS [u'%Y-%m-%d',
 u'%m/%d/%Y',
 u'%m/%d/%y',
 u'%b %d %Y',
 u'%b %d, %Y',
 u'%d %b %Y',
 u'%d %b, %Y',
 u'%B %d %Y',
 u'%B %d, %Y',
 u'%d %B %Y',
 u'%d %B, %Y']
 
DEBUG True
 
DEBUG_PROPAGATE_EXCEPTIONS False
 
DECIMAL_SEPARATOR u'.'
 
DEFAULT_CHARSET u'utf-8'
 
DEFAULT_CONTENT_TYPE u'text/html'
 
DEFAULT_EXCEPTION_REPORTER_FILTER u'django.views.debug.SafeExceptionReporterFilter'
 
DEFAULT_FILE_STORAGE u'django.core.files.storage.FileSystemStorage'
 
DEFAULT_FROM_EMAIL u'webmaster@localhost'
 
DEFAULT_INDEX_TABLESPACE u''
 
DEFAULT_MACHINE_GROUP_KEY u'********************'
 
DEFAULT_TABLESPACE u''
 
DEPLOYED_ON_CHECKIN False
 
DISALLOWED_USER_AGENTS []
 
DISPLAY_NAME 'Sal'
 
EMAIL_BACKEND u'django.core.mail.backends.smtp.EmailBackend'
 
EMAIL_HOST u'localhost'
 
EMAIL_HOST_PASSWORD u'********************'
 
EMAIL_HOST_USER u''
 
EMAIL_PORT 25
 
EMAIL_SSL_CERTFILE None
 
EMAIL_SSL_KEYFILE u'********************'
 
EMAIL_SUBJECT_PREFIX u'[Django] '
 
EMAIL_TIMEOUT None
 
EMAIL_USE_SSL False
 
EMAIL_USE_TLS False
 
EXCLUDED_CONDITIONS {}
 
EXCLUDED_FACTS set(['sshdsakey', 'sshfp_dsa', 'sshfp_rsa', 'sshrsakey'])
 
FILE_CHARSET u'utf-8'
 
FILE_UPLOAD_DIRECTORY_PERMISSIONS None
 
FILE_UPLOAD_HANDLERS [u'django.core.files.uploadhandler.MemoryFileUploadHandler',
 u'django.core.files.uploadhandler.TemporaryFileUploadHandler']
 
FILE_UPLOAD_MAX_MEMORY_SIZE 2621440
 
FILE_UPLOAD_PERMISSIONS None
 
FILE_UPLOAD_TEMP_DIR None
 
FIRST_DAY_OF_WEEK 0
 
FIXTURE_DIRS []
 
FORCE_SCRIPT_NAME None
 
FORMAT_MODULE_PATH None
 
HIDE_PLUGIN_FROM_BUSINESS_UNIT {}
 
HIDE_PLUGIN_FROM_FRONT_PAGE []
 
HIDE_PLUGIN_FROM_MACHINE_GROUP {}
 
HISTORICAL_DAYS 180
 
HISTORICAL_FACTS []
 
IGNORABLE_404_URLS []
 
INACTIVE_UNDEPLOYED 0
 
INSTALLED_APPS ('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'sal',
 'server',
 'api',
 'catalog',
 'inventory',
 'licenses',
 'bootstrap3',
 'watson',
 'datatableview',
 'search')
 
INTERNAL_IPS []
 
LANGUAGES [(u'af', u'Afrikaans'),
 (u'ar', u'Arabic'),
 (u'ast', u'Asturian'),
 (u'az', u'Azerbaijani'),
 (u'bg', u'Bulgarian'),
 (u'be', u'Belarusian'),
 (u'bn', u'Bengali'),
 (u'br', u'Breton'),
 (u'bs', u'Bosnian'),
 (u'ca', u'Catalan'),
 (u'cs', u'Czech'),
 (u'cy', u'Welsh'),
 (u'da', u'Danish'),
 (u'de', u'German'),
 (u'dsb', u'Lower Sorbian'),
 (u'el', u'Greek'),
 (u'en', u'English'),
 (u'en-au', u'Australian English'),
 (u'en-gb', u'British English'),
 (u'eo', u'Esperanto'),
 (u'es', u'Spanish'),
 (u'es-ar', u'Argentinian Spanish'),
 (u'es-co', u'Colombian Spanish'),
 (u'es-mx', u'Mexican Spanish'),
 (u'es-ni', u'Nicaraguan Spanish'),
 (u'es-ve', u'Venezuelan Spanish'),
 (u'et', u'Estonian'),
 (u'eu', u'Basque'),
 (u'fa', u'Persian'),
 (u'fi', u'Finnish'),
 (u'fr', u'French'),
 (u'fy', u'Frisian'),
 (u'ga', u'Irish'),
 (u'gd', u'Scottish Gaelic'),
 (u'gl', u'Galician'),
 (u'he', u'Hebrew'),
 (u'hi', u'Hindi'),
 (u'hr', u'Croatian'),
 (u'hsb', u'Upper Sorbian'),
 (u'hu', u'Hungarian'),
 (u'ia', u'Interlingua'),
 (u'id', u'Indonesian'),
 (u'io', u'Ido'),
 (u'is', u'Icelandic'),
 (u'it', u'Italian'),
 (u'ja', u'Japanese'),
 (u'ka', u'Georgian'),
 (u'kk', u'Kazakh'),
 (u'km', u'Khmer'),
 (u'kn', u'Kannada'),
 (u'ko', u'Korean'),
 (u'lb', u'Luxembourgish'),
 (u'lt', u'Lithuanian'),
 (u'lv', u'Latvian'),
 (u'mk', u'Macedonian'),
 (u'ml', u'Malayalam'),
 (u'mn', u'Mongolian'),
 (u'mr', u'Marathi'),
 (u'my', u'Burmese'),
 (u'nb', u'Norwegian Bokm\xe5l'),
 (u'ne', u'Nepali'),
 (u'nl', u'Dutch'),
 (u'nn', u'Norwegian Nynorsk'),
 (u'os', u'Ossetic'),
 (u'pa', u'Punjabi'),
 (u'pl', u'Polish'),
 (u'pt', u'Portuguese'),
 (u'pt-br', u'Brazilian Portuguese'),
 (u'ro', u'Romanian'),
 (u'ru', u'Russian'),
 (u'sk', u'Slovak'),
 (u'sl', u'Slovenian'),
 (u'sq', u'Albanian'),
 (u'sr', u'Serbian'),
 (u'sr-latn', u'Serbian Latin'),
 (u'sv', u'Swedish'),
 (u'sw', u'Swahili'),
 (u'ta', u'Tamil'),
 (u'te', u'Telugu'),
 (u'th', u'Thai'),
 (u'tr', u'Turkish'),
 (u'tt', u'Tatar'),
 (u'udm', u'Udmurt'),
 (u'uk', u'Ukrainian'),
 (u'ur', u'Urdu'),
 (u'vi', u'Vietnamese'),
 (u'zh-hans', u'Simplified Chinese'),
 (u'zh-hant', u'Traditional Chinese')]
 
LANGUAGES_BIDI [u'he', u'ar', u'fa', u'ur']
 
LANGUAGE_CODE 'en_GB'
 
LANGUAGE_COOKIE_AGE None
 
LANGUAGE_COOKIE_DOMAIN None
 
LANGUAGE_COOKIE_NAME u'django_language'
 
LANGUAGE_COOKIE_PATH u'/'
 
LIMIT_PLUGIN_TO_FRONT_PAGE []
 
LOCALE_PATHS []
 
LOGGING {'disable_existing_loggers': False,
 'formatters': {'simple': {'format': '%(levelname)s %(message)s'},
                'verbose': {'datefmt': '%d/%b/%Y %H:%M:%S',
                            'format': '[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s'}},
 'handlers': {'file': {'class': 'logging.FileHandler',
                       'filename': 'sal.log',
                       'formatter': 'verbose',
                       'level': 'ERROR'}},
 'loggers': {'django': {'handlers': ['file'],
                        'level': 'ERROR',
                        'propagate': True},
             'sal': {'handlers': ['file'], 'level': 'ERROR'}},
 'version': 1}
 
LOGGING_CONFIG u'logging.config.dictConfig'
 
LOGIN_REDIRECT_URL '/'
 
LOGIN_URL '/login'
 
LOGOUT_REDIRECT_URL None
 
MANAGERS ()
 
MEDIA_ROOT ''
 
MEDIA_URL ''
 
MESSAGE_STORAGE u'django.contrib.messages.storage.fallback.FallbackStorage'
 
MIDDLEWARE None
 
MIDDLEWARE_CLASSES ('django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'server.middleware.AddToBU.AddToBU',
 'search.current_user.CurrentUserMiddleware')
 
MIGRATION_MODULES {}
 
MONTH_DAY_FORMAT u'F j'
 
NUMBER_GROUPING 0
 
PASSWORD_HASHERS u'********************'
 
PASSWORD_RESET_TIMEOUT_DAYS u'********************'
 
PLUGIN_DIR '/home/docker/sal/plugins'
 
PLUGIN_ORDER ['Activity',
 'Status',
 'OperatingSystem',
 'MunkiVersion',
 'Uptime',
 'Memory',
 'DiskSpace',
 'PendingAppleUpdates',
 'Pending3rdPartyUpdates',
 'PuppetStatus']
 
PREPEND_WWW False
 
PROJECT_DIR '/home/docker/sal'
 
ROOT_URLCONF 'sal.urls'
 
SECRET_KEY u'********************'
 
SECURE_BROWSER_XSS_FILTER False
 
SECURE_CONTENT_TYPE_NOSNIFF False
 
SECURE_HSTS_INCLUDE_SUBDOMAINS False
 
SECURE_HSTS_SECONDS 0
 
SECURE_PROXY_SSL_HEADER None
 
SECURE_REDIRECT_EXEMPT []
 
SECURE_SSL_HOST None
 
SECURE_SSL_REDIRECT False
 
SERVER_EMAIL u'root@localhost'
 
SESSION_CACHE_ALIAS u'default'
 
SESSION_COOKIE_AGE 1209600
 
SESSION_COOKIE_DOMAIN None
 
SESSION_COOKIE_HTTPONLY True
 
SESSION_COOKIE_NAME u'sessionid'
 
SESSION_COOKIE_PATH u'/'
 
SESSION_COOKIE_SECURE False
 
SESSION_ENGINE u'django.contrib.sessions.backends.db'
 
SESSION_EXPIRE_AT_BROWSER_CLOSE False
 
SESSION_FILE_PATH None
 
SESSION_SAVE_EVERY_REQUEST False
 
SESSION_SERIALIZER u'django.contrib.sessions.serializers.JSONSerializer'
 
SETTINGS_MODULE 'sal.settings'
 
SHORT_DATETIME_FORMAT u'm/d/Y P'
 
SHORT_DATE_FORMAT u'm/d/Y'
 
SIGNING_BACKEND u'django.core.signing.TimestampSigner'
 
SILENCED_SYSTEM_CHECKS []
 
SITE_ID 1
 
SSH_ACCOUNT None
 
STATICFILES_DIRS ('/home/docker/sal/site_static',)
 
STATICFILES_FINDERS ('django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder')
 
STATICFILES_STORAGE u'django.contrib.staticfiles.storage.StaticFilesStorage'
 
STATIC_ROOT '/home/docker/sal/static'
 
STATIC_URL '/static/'
 
TEMPLATES [{'APP_DIRS': True,
  'BACKEND': 'django.template.backends.django.DjangoTemplates',
  'DIRS': ['/home/docker/sal/templates',
           '/home/docker/sal/server/plugins',
           '/home/docker/sal/plugins'],
  'OPTIONS': {'autoescape': False,
              'context_processors': ['django.template.context_processors.debug',
                                     'django.template.context_processors.request',
                                     'django.contrib.auth.context_processors.auth',
                                     'django.contrib.messages.context_processors.messages',
                                     'sal.context_processors.display_name',
                                     'sal.context_processors.sal_version'],
              'debug': False}}]
 
TEST_NON_SERIALIZED_APPS []
 
TEST_RUNNER u'django.test.runner.DiscoverRunner'
 
THOUSAND_SEPARATOR u','
 
TIME_FORMAT u'P'
 
TIME_INPUT_FORMATS [u'%H:%M:%S', u'%H:%M:%S.%f', u'%H:%M']
 
TIME_ZONE 'Europe/London'
 
USE_ETAGS False
 
USE_I18N True
 
USE_L10N True
 
USE_THOUSAND_SEPARATOR False
 
USE_TZ True
 
USE_X_FORWARDED_HOST False
 
USE_X_FORWARDED_PORT False
 
WSGI_APPLICATION 'sal.wsgi.application'
 
X_FRAME_OPTIONS u'SAMEORIGIN'
 
YEAR_MONTH_FORMAT u'F Y'
 

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard page generated by the handler for this status code.

**Comment by grahamgilbert** [comment]
This was fixed in maser yesterday and will be in he next release.

**Comment by jsummers1994** [comment]
Thank you, just re-built Sal and license section is now working.
