### ISSUE TITLE
Crypt Machine Plugin tracebacks when URL not set

### ISSUE THREAD

**Issue by erikng** [salopensource/sal#130]
Tracking this so I don't forget.

https://github.com/salopensource/sal/blob/master/server/plugins/cryptstatus/cryptstatus.py

I also owe you a documentation for the plugin on the wiki

**Comment by erikng** [comment]
Why did you close this? I just haven't had time to do it.

**Comment by clburlison** [comment]
Because the trace back is fixed.

**Comment by erikng** [comment]
Ah okay. I haven't been keeping up with slack lately. Carry on.

**Comment by clburlison** [comment]
For reference purposes here are the PRs that fixed this bug #151 and #156. Looks like we didn't tag this issue.
