### ISSUE TITLE
bad permissions

### ISSUE THREAD

**Issue by fuzzycheck** [salopensource/sal#161]
Hi,

the Dockerfile sets RWX for everyone.

chmod 777 $APP_DIR/sal.log

Regards,
Fuzzycheck

**Comment by grahamgilbert** [comment]
Okay... what’s the problem though?

**Comment by fuzzycheck** [comment]
well, if it disturbs no one, that's not a problem.
I can only imagine a scenario where a colleague would enter the container, and type "./sal.log" instead of "less ./sal.log", and some stacktrace in there was containing something resembling a shell command.
But people would rarely do that.

**Comment by grahamgilbert** [comment]
If you have humans accessing the box you have other problems to be fair...
