### ISSUE TITLE
Work towards Django 2.0 / python3!

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal#163]
Django support for python 2.7 ended (today) with Django 1.11 going into LTS. Django 1.11 will continue to get security fixes until 2020, but python3 shouldn't be hard to upgrade to.

**Comment by sheagcraig** [comment]
A reminder-maybe it will work just fine, but middleware may need a very minor touch up for this.

Django 2.0 activates class-based middleware with `MIDDLEWARE` instead of `MIDDLEWARE_CLASSES`.

Also, middleware classes should have an `__init__` that accepts one argument, so inheriting the default from  `object` may not work.

**Comment by clburlison** [comment]
- [ ] Rename `search_maintenance`/`search_maint.sh` to `maintenance`/`maint.sh`

Since we are putting other things into this function we should rename it to match what it is actually doing.

**Comment by sheagcraig** [comment]
Py3 is merged into the 4.0.0 branch.

Next step will be updating Django.
