### ISSUE TITLE
Show 'deployed' key-value on machine detail page

### ISSUE THREAD

**Issue by ChefAustin** [salopensource/sal#166]
Currently there is no reference to machine's deployment status on a 'machine_detail' page. Would be nice for a user to see whether or not that machine was in circulation or in storage (at least in my case).

I believe the only place this is explicitly shown is via the 'status' plugin, and it could be a benefit to the user if that attribute was displayed on an additional page.

**Comment by w0de** [comment]
Technically a feature request, I know. I'm adding it to our fork, I'll pull request when done.

**Comment by ChefAustin** [comment]
Appending the below block to [line 113 in server/templates/server/machine_detail.html](https://github.com/salopensource/sal/blob/68db95c42086d833d5a85a022f3781098c397394/server/templates/server/machine_detail.html#L113) should do it, right?

```
          <dt>Deployed:</dt>
          <dd>
            {{ machine.deployed }}
          </dd>
```

**Comment by grahamgilbert** [comment]
Sort of, just that will just display True or False. We may want to make that a bit nicer.

**Comment by grahamgilbert** [comment]
Probably something like this would be better (written here, not tested):

```
<dt>Deployment status:</dt>
          <dd>
            {% if machine.deployed %}
            Deployed
            {% else %}
            Undeployed
            {% endif %}
          </dd>
```
