### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by chasetb** [salopensource/sal#2]
Getting an internal server error page when trying to access Sal after just completing the install instructions for Ubuntu 14. I created a gist of the error.log here: https://gist.github.com/chasetb/3e867e455638cb0e932a

Looks like the issues is either an issue with mod_wsgi or something in the AppRegistry. Any ideas?

**Comment by chasetb** [comment]
I did some web searching and found that some older code needed to be updated for Django 1.7 and above. Here are the changes I made: https://github.com/chasetb/sal/commit/f9b86649073737f0bca769f815ec5e9c8c9f0248

**Comment by grahamgilbert** [comment]
Can we close this now, it's been sorted in https://github.com/salopensource/sal/pull/1, right?

**Comment by chasetb** [comment]
Yep. Thanks.
