### ISSUE TITLE
API timestamp format changed

### ISSUE THREAD

**Issue by keeleysam** [salopensource/sal#205]
A recent version of Sal changed the format of the timestamp on the v1 API, which broke some of our tooling as it wasn't expecting the change in format.

I'm not sure what it was before, but I don't think it had the timezone at the end.

It's currently sending down timestamps like `2018-02-12T11:44:52-08:00`, which the Chronic rubygem doesn't parse.

cc: @sheagcraig

**Comment by sheagcraig** [comment]
That's interesting. I'm pretty sure nothing was supposed to have changed on the v1 API.

**Comment by sheagcraig** [comment]
@keeleysam ^^^ ?
