### ISSUE TITLE
Cannot use with Postgres > 9 due to psycopg2

### ISSUE THREAD

**Issue by rickmark** [salopensource/sal#218]
From my understanding, psycopg2@2.6 has a defect that makes it impossible to use with posgres where postgres is greater then 9.  It seemed to be easily resolved by moving the dependency up to 2.7.1

I'll perform more compatibility testing and baring issues attach a pull request.

**Comment by sheagcraig** [comment]
https://github.com/salopensource/sal/blob/master/requirements.txt#L3
