### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by mholtrlc** [salopensource/sal#22]
Hey,

Was going to update my docker container to the latest release and newest version is Sal-LDAP is 2.1.1.  When will you be pushing the new image?

**Comment by grahamgilbert** [comment]
Tomorrow most likely - the LDAP image is usually a couple of days behind the main release.

**Comment by mholtrlc** [comment]
ok Thanks!

[image: Real Life Church] <http://www.reallifechurch.org>

Michael Holt / IT Administrator
(661) 705-4711/ mholt@reallifechurch.org

Real Life Church Office: (661) 775-7401
23841 Newhall Ranch Rd
Valencia, CA 91355
http://www.reallifechurch.org

This e-mail message may contain confidential or legally privileged
information and is intended only for the use of the intended recipient(s).
Any unauthorized disclosure, dissemination, distribution, copying or the
taking of any action in reliance on the information herein is prohibited.
E-mails are not secure and cannot be guaranteed to be error free as they
can be intercepted, amended, or contain viruses. Anyone who communicates
with us by e-mail is deemed to have accepted these risks. Company Name is
not responsible for errors or omissions in this message and denies any
responsibility for any damage arising from the use of e-mail. Any opinion
and other statement contained in this message and any attachment are solely
those of the author and do not necessarily represent those of the company.
