### ISSUE TITLE
Unable to change password

### ISSUE THREAD

**Issue by seraphimalia** [salopensource/sal#225]
Hi, I have just installed a fresh installation of sal on OSX High Sierra (I followed the "Starting Sal" instructions here: https://github.com/salopensource/sal/wiki/Getting-Started - with some slight modifications to resolve the docker file permissions issue for postgres by using a docker volume, and the host port forwarding issue with virtualbox by adding a port forward rule).  When I click Change Password I am presented with the following error.  Please help?

> TemplateSyntaxError at /changepassword/
> 'future' is not a registered tag library. Must be one of:
> admin_list
> admin_modify
> admin_static
> admin_urls
> bootstrap3
> cache
> dashboard_extras
> i18n
> l10n
> log
> static
> staticfiles
> tz
> watson
> Request Method:	GET
> Request URL:	http://sal.addynamo.net/changepassword/
> Django Version:	1.10
> Exception Type:	TemplateSyntaxError
> Exception Value:	
> 'future' is not a registered tag library. Must be one of:
> admin_list
> admin_modify
> admin_static
> admin_urls
> bootstrap3
> cache
> dashboard_extras
> i18n
> l10n
> log
> static
> staticfiles
> tz
> watson
> Exception Location:	/usr/local/lib/python2.7/dist-packages/django/template/base.py in parse, line 518
> Python Executable:	/usr/bin/python
> Python Version:	2.7.6
> Python Path:	
> ['/home/docker/sal',
>  '/usr/local/bin',
>  '/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg',
>  '/home/docker/sal',
>  '/usr/lib/python2.7',
>  '/usr/lib/python2.7/plat-x86_64-linux-gnu',
>  '/usr/lib/python2.7/lib-tk',
>  '/usr/lib/python2.7/lib-old',
>  '/usr/lib/python2.7/lib-dynload',
>  '/usr/local/lib/python2.7/dist-packages',
>  '/usr/lib/python2.7/dist-packages']

**Comment by grahamgilbert** [comment]
Which version are you seeing this on?

**Comment by knightsc** [comment]
It looks like this might have just been because the getting started guide specified an old 3.0.3 version of SAL. I edited the wiki page for it to just reference the latest tag so it would pull the most up to date docker images
