### ISSUE TITLE
Munki Installs plugin is reporting incorrectly

### ISSUE THREAD

**Issue by blackthroat** [salopensource/sal#260]
The Munki Installs plugin is not performing as expected as my fleet of approximately 300 machines has never seen over 500 installs in a single day.

![image](https://user-images.githubusercontent.com/25038086/42035873-919f49ea-7aa9-11e8-92a4-7f23ac42677c.png)

Per heimdall from MacAdmins Slack:
> It counts the lines outputted in post install after installation of software occurs, however, I think what it is supposed to be doing is show how much software was installed on the fleet of machines after you push updates.
> 
> As a historical metric.

In addition to this, it would be nice to have the ability to adjust the date range:

https://github.com/salopensource/sal/blob/f1425a0d15145d9e328ba60f35baaba43fd28217/server/plugins/munkiinstalls/munkiinstalls.py#L23

The widget_width would most likely need to scale proportionately or be adjustable as well:

https://github.com/salopensource/sal/blob/f1425a0d15145d9e328ba60f35baaba43fd28217/server/plugins/munkiinstalls/munkiinstalls.py#L16

**Comment by grahamgilbert** [comment]
Your guess on how the plugin works isn’t reflected by the code. It sums the number of installs items for that day.  I would bet that you will see a corresponding number of installs items in the admin site. If not, then I would suggest looking at the query in the plugin to see where it is going wrong. If the number recorded is reflected accurately by the plugin, then I would be interested if it is continuing or if that was an anomaly during the upgrade. 

As to your feature requests - I’m sure you can work that out and PR it based on other plugins that read from setting.

**Comment by epackorigan** [comment]
@blackthroat - i'm seeing the same here, and i just updated sal on the server from 3.2.14 to 3.3.7.
I'm in the process of deploying the new sal_script to go along with it (2.0.7 -> 2.1.3). Could it be that the sal_script setup has a slightly different format that reports differently?
(just making a guess here)

**Comment by grahamgilbert** [comment]
No, nothing changed on this front. The munki report is still the munki report.

**Comment by grahamgilbert** [comment]
This is likely fixed in current master.
