### ISSUE TITLE
Feature: Add Configuration Items

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal#264]
@grahamgilbert, @weswhet and I discussed this at PSU.

This is a feature change to Sal which will abstract some of the Mac/Munki specific stuff into a "Configuration Items" (name TBD) model that can then include arbitrary configuration sources' managed items. This is specifically, currently, Munki managed installs/uninstalls and their install history.

In the future, we'd also be able to include states (Salt)/plays (Ansible)/etc (Puppet, Chef), as well as information for non-macOS clients (Chocolatey), ChromeOS "stuff"; the list goes on.

The current thinking is to add two models:
- Configuration Source: A configuration provider, matched with a corresponding plugin on the client side, that can provide information about configuration items (i.e. "Ansible", "Munki", "Puppet").
- Configuration Item: An actual item of interest. This model would include some generally useful fields, as well as a dictionary (name: "metadata"? "details"?) that could then include as much information as the plugin wants to offer up.

As it stands, this information is primarily displayed on the machine detail page. So this will also include a redesign of that page to split up the righthand column by configuration source, and then by configuration items. We'll probably have to do some javascript to do detail dialogs or disclosure-triangle details since in most cases the user will probably just want to see the state and name of a configuration item.

I have a photo of the flipboard we wrote on that I'll use to write up a model proposal soon.

**Comment by sheagcraig** [comment]
I'm going to add a field that will indicate whether a configuration item is active or not; specifically, clients checking in will keep updating status. But, say for example that you remove an item from a Munki manifest. Now it's no longer in any of the machine's manifests, but there's still history of it in the Sal database. I imagine to help differentiate between current configurations and past ones, we'll need a field, and probably we can have the historical ones appear greyed out or in a different column.

Then, we can treat them with the same retention policy used for other items, and clean them up once they're no-longer-active and have a date older than the retention policy.

**Comment by sheagcraig** [comment]
I'm not as familiar with the structure, but I think we should use this opportunity to look at machine data as well. Sal currently collects machine data from Munki and from facter. I'll look into what it would take to modularize this too, so we can dump salt grains in, or ansible facts, etc.

When I get a better idea of what this would look like, I'll ask around about implementation details and what changes to the UI make the most sense. Just wanted to throw this out so others can comment and think about it.

**Comment by NoahRJ** [comment]
I know it's been a few months since this issue has been opened, but I'd definitely +1 this. We're looking at Sal with Facter for additional extensibility, but Ansible is a framework my team is most familiar with, so being able to leverage Ansible facts would be huge.

**Comment by lashomb** [comment]
Ansible would be great, especially as it can already consume facts from facter and ohai.

**Comment by weswhet** [comment]
@NoahRJ @lashomb You could easy PR ansible facts for sal-scripts, you can use SaltGrains, and ChefOhia as an example. This would cause ansible facts to show up as Facter on current versions of Sal.

**Comment by aschwanb** [comment]
I'm putting the two functions @weswhet mentioned in here for reference. I hope I found the right ones: [SaltGrains](https://github.com/salopensource/sal-scripts/blob/master/payload/usr/local/sal/bin/sal-submit#L399) and [ChefOhai](https://github.com/salopensource/sal-scripts/blob/master/payload/usr/local/sal/bin/sal-submit#L317)

**Comment by sheagcraig** [comment]
ManagedItems
* FK -> Machine
* FK -> ManagementSource
* ID
* Datetime (checkin time or last managed time; e.g. salt run time)
* Name (managed install name, salt state name)
* Type (managed install, managed uninstall, state, optional install, pending install, etc)
* Status (installed, pending, not installed, successful, failure) we should map these onto a handful of acceptable statuses for display, like: OK, Failed, Pending, Unknown
* Retention: Whether this item should be deleted on every checkin or retained for some period of time.
* data: json (possibly b64/bz2 encoded) dict of key (display header/type) value pairs.
    * Comment: Optional text field to display (salt has a comment in its output)
    * Version (munki items have version numbers. CM stuff doesn’t really.
ManagementSource
* ID
* Name

The “data” flexibility seems like an acceptable tradeoff in performance since it’s really only used when viewing a machine detail page and when checking in / updating install history for munki items.

Example of Salt ManagedItem:
* FK to Machine “Shea’s PowerMac G3"
* FK to ManagementSource “Salt"
* ID: 2323423235
* datetime: 2019-01-30T13:00:00Z
* name: Configure NoMAD pref UseKeychainPrompt
* type: state
* status: okay
* retention: None (erase and recreate every run)
* data
    * function: prefs.exists
    * comment: com.trusourcelabs.NoMAD UseKeychainPrompt is already set to True
    * duration: 0.366 ms
    * changes: None
Example of Munki item
* FK to Machine “Shea’s PowerMac G3"
* FK to ManagementSource “Munki"
* ID: 2323423235
* datetime: 2019-01-30T13:00:00Z
* name: Dwarf Fortress
* type: ManagedInstall
* status: okay
* retention: None (erase and recreate every run)
* data
    * version: 0.44.12
    * description: Dwarf Fortress is a single-player fantasy game. You can control a dwarven outpost or an adventurer in a randomly generated, persistent world.
    * installed_size: 170857

To get started with, I’ll probably update the machine detail page to display all managed items much like the current page displays munki managed installs, pending installs, managed uninstalls (i.e a tabbed top menu corresponding to the ManagementSource, with dropdown selection for “type”). Then the managed items will be sorted and displayed. Probably name and status, with some method to get more info. The existing update history dialog that you get from clicking on the status of a managed install could be reused for this purpose.
The dialog / full view would then include all of the data: all of the previous info, but also the “data” section, again sorted and printed so that a table can be created from the key/value pairs.

It's a lot easier to change the design before I start coding, so let me know if I'm missing something obvious here!

**Comment by grahamgilbert** [comment]
I think we should use ULIDs rather than plain IDs for future proofing. One of my “someday” projects is to work out how to move the other models to them.

**Comment by sheagcraig** [comment]
Whoa. Fancy. How would we go about doing that? I was just going to let it use the normal auto ID.

**Comment by grahamgilbert** [comment]
We just need to find a suitable library and in places where I’ve used bigint for example we can use a ulid. 

This looks suitable from a 3 second google https://github.com/valohai/ulid2/blob/master/README.md

**Comment by sheagcraig** [comment]
Okay; make the call and I'll do that for the two new ones. It's as simple as adding ulid2 to the requirements.txt and

```
from django.db import models
from ulid2 import generate_ulid_as_uuid

class MyModel(models.Model):
    id = models.UUIDField(default=generate_ulid_as_uuid, primary_key=True)
```

**Comment by sheagcraig** [comment]
As for other models, I'll throw an issue/FR up to switch them.

Can we do a migration that just goes through the entire DB and creates a ULID for each ID that is just an int now?
