### ISSUE TITLE
Unexpected return no values

### ISSUE THREAD

**Issue by jokdbx** [salopensource/sal#265]
https://github.com/salopensource/sal/blob/94fbce904d928b65e092ca23d0541d54bd94c930/server/non_ui_views.py#L332-L335

It appears that if the checking doesn't contain a report, we just return with no value. Is this correct?

* Shouldn't this return a HttpResponse?
* Since we're not using `machine.save()` before the return, are the few previous lines before it useless? (or is there more meaning behind this that i'm not seeing?)

**Comment by grahamgilbert** [comment]
I believe this to be correct. `report` is a required part of the checkin for all platforms, and there are many fields we get from it. This should at least raise some sort of error though (I'm not sure of the appropriate code - maybe `403` @sheagcraig ?).

**Comment by sheagcraig** [comment]
Handled! This is out with the new checkin code.
