### ISSUE TITLE
application inventory machine list has too many items

### ISSUE THREAD

**Issue by jokdbx** [salopensource/sal#266]
the url `inventory/application/all/0/472/` will report the right number for each version, but when clicking on one of the version item (`inventory/list/all/0/472/?field_type=version&field_value=6.6.2`) yields a list much larger than the version list called for.

it looks like the list includes many machines where the item is present, but the `Install Count` field is 0.

(in my example, i have a first link showing 1 installed items for keynote, but the list of machine is 74 machines, 1 of which have `Install Count` set to `1`, all the others have `0` -- I expect the later should be filtered out of the set. I don't quite understand how that works in `inventory/views.py`)

I am using postgres 9.5 on Ubuntu 16.04 (no docker)

**Comment by sheagcraig** [comment]
Ahhhh, a classic blunder,

This predates deeper understanding of the queryset API...

`x.filter(a='x').filter(b='y')` != `x.filter(a='x', b='y')`!

Sometimes you can get away with it and it doesn't matter, but sometimes it _does_ matter.

Check out #276
