### ISSUE TITLE
Sal - Machine widget not loading

### ISSUE THREAD

**Issue by jsummers1994** [salopensource/sal#267]
I have installed and updated Sal onto a new server and one of the machine widget tools is not loading. I just get a spinning loading wheel. The widget is located between the remote connection widget and apple remote desktop computer information. Does anyone know what this widget tool is and how i can get it to work? Kind Regards, Jack.

**Comment by grahamgilbert** [comment]
Look at your browsers error console. Widgets can be placed wherever you want so we are literally flying blind here.

**Comment by grahamgilbert** [comment]
Enable debug, hit the url listed in the error directly and see what the error is. I assume you have configured your crypt url correctly in the admin pane?

**Comment by jsummers1994** [comment]
'NoneType' object has no attribute 'rstrip'

However this is not a plugin that I use so I have removed it from the machine details page.

**Comment by grahamgilbert** [comment]
I guarantee there is more in the error. It would give things like a line number.

**Comment by jsummers1994** [comment]
Request Method: | GET
-- | --
http://odms04.aspire.don.ac.uk:8008/load_plugin/CryptStatus/machine/6/
1.10
AttributeError
'NoneType' object has no attribute 'rstrip'
/home/docker/sal/server/plugins/cryptstatus/cryptstatus.py in get_context, line 22
/usr/bin/python
2.7.6
['/home/docker/sal',  '/usr/local/lib/python2.7/dist-packages/pip-10.0.1-py2.7.egg',  '/home/docker/sal',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Tue, 24 Jul 2018 14:33:25 +0100

Traceback
Environment:


Request Method: GET
Request URL: http://odms04.aspire.don.ac.uk:8008/load_plugin/CryptStatus/machine/6/

Django Version: 1.10
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'sal',
 'server',
 'api',
 'catalog',
 'inventory',
 'licenses',
 'profiles',
 'bootstrap3',
 'datatableview',
 'search',
 'rest_framework',
 'django_filters')
Installed Middleware:
('django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'server.middleware.AddToBU.AddToBU',
 'search.current_user.CurrentUserMiddleware')



Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/home/docker/sal/server/non_ui_views.py" in plugin_load
  142.         plugin_object.widget_content(request, group_type=group_type, group_id=group_id))

File "/home/docker/sal/sal/plugin.py" in widget_content
  238.         context = self.get_context(queryset, **kwargs)

File "/home/docker/sal/server/plugins/cryptstatus/cryptstatus.py" in get_context
  22.         crypt_url = utils.get_setting('crypt_url', None).rstrip()

Exception Type: AttributeError at /load_plugin/CryptStatus/machine/6/
Exception Value: 'NoneType' object has no attribute 'rstrip'

**Comment by jsummers1994** [comment]
I dont know if this is solved. After pulling down and applying the changed i get the following new error.

Request Method: | GET
-- | --
http://odms04.aspire.don.ac.uk:8008/load_plugin/CryptStatus/machine/7/
1.10
UnboundLocalError
local variable 'machine_url' referenced before assignment
/home/docker/sal/server/plugins/cryptstatus/cryptstatus.py in get_context, line 51
/usr/bin/python
2.7.6
['/home/docker/sal',  '/usr/local/lib/python2.7/dist-packages/pip-18.0-py2.7.egg',  '/home/docker/sal',  '/usr/lib/python2.7',  '/usr/lib/python2.7/plat-x86_64-linux-gnu',  '/usr/lib/python2.7/lib-tk',  '/usr/lib/python2.7/lib-old',  '/usr/lib/python2.7/lib-dynload',  '/usr/local/lib/python2.7/dist-packages',  '/usr/lib/python2.7/dist-packages']
Tue, 24 Jul 2018 16:37:29 +0100



Environment:


Request Method: GET
Request URL: http://odms04.aspire.don.ac.uk:8008/load_plugin/CryptStatus/machine/7/

Django Version: 1.10
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'sal',
 'server',
 'api',
 'catalog',
 'inventory',
 'licenses',
 'profiles',
 'bootstrap3',
 'datatableview',
 'search',
 'rest_framework',
 'django_filters')
Installed Middleware:
('django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'server.middleware.AddToBU.AddToBU',
 'search.current_user.CurrentUserMiddleware')



Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py" in inner
  39.             response = get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/home/docker/sal/server/non_ui_views.py" in plugin_load
  142.         plugin_object.widget_content(request, group_type=group_type, group_id=group_id))

File "/home/docker/sal/sal/plugin.py" in widget_content
  238.         context = self.get_context(queryset, **kwargs)

File "/home/docker/sal/server/plugins/cryptstatus/cryptstatus.py" in get_context
  51.         context['crypt_url'] = machine_url

Exception Type: UnboundLocalError at /load_plugin/CryptStatus/machine/7/
Exception Value: local variable 'machine_url' referenced before assignment

**Comment by grahamgilbert** [comment]
To be honest, if you don't configure the plugin it isn't going to work anyway... It should just stop processing if the setting isn't there and be done with it.

**Comment by jsummers1994** [comment]
Agreed if I'm not going to use the plugin. Just in case anyone else comes up with the same problem. Thank you for your help, Jack.
