### ISSUE TITLE
Pending updates showing older version number when multiple versions are pending.

### ISSUE THREAD

**Issue by duel007** [salopensource/sal#27]
As discussed on the mailing list, updates are showing in the pending section as an older version (14.5.7) when a newer version is available and approved, and there are clients pending installs of both versions. See attached screenshots. All clients are on version 0.6.1 of the Sal scripts.
![sal1](https://cloud.githubusercontent.com/assets/5648179/11123078/b5cee3d6-8923-11e5-8199-b22c58c9ec74.PNG)
![sal2](https://cloud.githubusercontent.com/assets/5648179/11123080/b5d758cc-8923-11e5-855c-972f78715863.PNG)
![sal3](https://cloud.githubusercontent.com/assets/5648179/11123079/b5d7eada-8923-11e5-841e-68049f2e44eb.PNG)

**Comment by grahamgilbert** [comment]
This happens [here](https://github.com/salopensource/sal/blob/master/server/plugins/pending3rdpartyupdates/pending3rdpartyupdates.py#L37-L41). I should take into account versions as well when testing uniqueness. Schedule permitting I'll take a look tomorrow.

**Comment by grahamgilbert** [comment]
This has been addressed.

**Comment by duel007** [comment]
Thanks for jumping on this, Graham. I'll watch for the new build to be pushed to docker.
