### ISSUE TITLE
Version number "0" appended to software titles in Pending3rd Party Updates table

### ISSUE THREAD

**Issue by bfreezy** [salopensource/sal#274]
I've recently setup Sal server - version 3.3.8.1530 - and distributed the sal_scripts and puppet facter to my machines.

I've noticed that the Pending3rdParty Updates table appends a "0" to the end of Software Titles, rather than the actual version.

Example:

![screen shot 2018-08-07 at 11 43 22 am](https://user-images.githubusercontent.com/23509619/43794463-e6a0e1ba-9a43-11e8-8bf9-35cb7dd94f60.png)

In this example, let's focus on the AWSCLI pending install.  I went to the client and inspected the ManagedInstallReport.plist, which has these entries around AWSCLI:

```
	<key>ConsoleUser</key>
	<string>adamjenkins</string>
	<key>EndTime</key>
	<string>2018-08-07 15:49:01 +0000</string>
	<key>Errors</key>
	<array/>
	<key>InstallResults</key>
	<array>
		<dict>
			<key>applesus</key>
			<false/>
			<key>display_name</key>
			<string>AWSCLI</string>
			<key>download_kbytes_per_sec</key>
			<integer>9856</integer>
			<key>duration_seconds</key>
			<integer>191</integer>
			<key>name</key>
			<string>AWSCLI</string>
			<key>status</key>
			<integer>0</integer>
			<key>time</key>
			<date>2018-08-07T15:47:29Z</date>
			<key>unattended</key>
			<true/>
			<key>version</key>
			<string>1.15.71</string>
		</dict>
```

Further down in the file....

```
	<key>ItemsToInstall</key>
	<array>
		<dict>
			<key>description</key>
			<string>Downloads the latest version of Amazon EC2 Tools and creates a package for deployment.</string>
			<key>display_name</key>
			<string>AWSCLI</string>
			<key>download_kbytes_per_sec</key>
			<integer>9856</integer>
			<key>icon_name</key>
			<string>awscli.png</string>
			<key>installed</key>
			<false/>
			<key>installed_size</key>
			<integer>9875</integer>
			<key>installer_item</key>
			<string>AWSCLI-1.15.71.pkg</string>
			<key>installer_item_size</key>
			<integer>9856</integer>
			<key>name</key>
			<string>AWSCLI</string>
			<key>unattended_install</key>
			<true/>
			<key>version_to_install</key>
			<string>1.15.71</string>
		</dict>
```

When checking the ApplicationInventory.plist from the client, I did not see any references to AWSCLI.

I would expect the Pending3rd Party Update table to show version 1.15.71 for the AWSCLI title.  It seems this is happening on every title that ends up in the Pending3rdParty table.  I am not seeing this issue on the Pending Apple Updates - those are fine.

![screen shot 2018-08-07 at 1 25 12 pm](https://user-images.githubusercontent.com/23509619/43794912-6245e7ec-9a45-11e8-8245-3d064cfd57fd.png)

Extra background - my clients were reporting to Munki Report, but I cleared out the MunkiReport binaries and cache files as part of my Sal rollout.

I'm happy to investigate further but wanted to file an issue just in case others are seeing the same behavior.

Thanks,
Brandon

**Comment by sheagcraig** [comment]
So if you look at https://github.com/salopensource/sal/blob/master/server/non_ui_views.py#L474, that's where the zero is almost certainly coming from.

Can you confirm that your Pending3rdParty items have gotten `update_version` of 0 saved?

If you look just a bit higher:
https://github.com/salopensource/sal/blob/master/server/non_ui_views.py#L470
it checks the `installed` key. If it gets anything from that (should be either `True` or `False`, it sets that as the `installed` value.

Then it determines the name of the version key based on that; so if `installed` is `True`, the version should be called `installed_version`. Otherwise, it uses `version_to_install`.

So my guess is that I made a mistake here where somehow the `installed` value ends up being True for pending updates, so that they're then looking up the version with the wrong key, and falling back to the default value of `0`.

I still don't see it, unfortunately. In your example, `installed` is `False`, so it should be using the `version_to_install` key, which is definitely present in the that record.

I thought it could be the model defaulting in a zero, but it's definitely set to allow null and blank, and has no default.

**Comment by sheagcraig** [comment]
I'll need to run this in the debugger to see what's going on here.

**Comment by bfreezy** [comment]
How would I check the `update_version` values for Pending3rdParty items?  Is that server side?

I looked at the code - I'd be curious to see what the output of `installed` is right after line 470 as well as knowing what `version_key` is right after line 473 so we could confirm that keys used for lookup are what we expect them to be.

Also, for reference, most of my Munki clients are v.3.3.1.3537.

**Comment by w0de** [comment]
bfreezy, that data should be generated by the sal-submit script. I keep a hacked version around which outputs submission & report to a file on disk for perusal. I'll clean it up and share it for your use, give me a couple hours to get time :)

**Comment by sheagcraig** [comment]
I'm not running a particularly current version here, so I don't have much data to go off of. While I wasn't able to replicate the exact issue, I did have some other issues that I suspect are actually the same one under the hood (different symptoms).

#277  should handle this. Give it a test and let me know.

Of note, any PendingUpdate objects are going to just hang out indefinitely after this change since the checkin will no longer make any. But the plugins don't actually use them.

**Comment by w0de** [comment]
Ok, bfreezy, if you find it helpful, clone my fork of sal-scripts and run `sudo python payload/usr/local/sal/bin/sal-submit --raw-output > filename` and you should be able to easily inspect the output sent to sal server in `filename`.

**Comment by bfreezy** [comment]
Just launched a container based off of the `fix_issue_274` branch.

I am now seeing versions numbers populate correctly in the Pending3rdParty Updates table

![screen shot 2018-08-09 at 3 30 38 pm](https://user-images.githubusercontent.com/23509619/43924266-c4fa8f3c-9be9-11e8-8600-4c35438fdeb4.png)

Thanks!

**Comment by bfreezy** [comment]
I've noticed one hiccup after running off the `fix_issue_274` branch.

Every link on the Pending3rd Party Updates table takes me to an error page.  Let's use the Google Chrome 68.0.3440.106 as an example.

I click it and the URI is:

https://sal.myserver.com/list/Pending3rdPartyUpdates/GoogleChrome--68.0.3440.106/all/0/

Error page:

<img width="467" alt="screen shot 2018-08-09 at 7 43 25 pm" src="https://user-images.githubusercontent.com/23509619/43932967-997d9c5a-9c0c-11e8-95fb-e6fce92a0dc0.png">

I have the same issue with every other item and it happens within each business unit as well.

I checked my Sal server logs but didn't really find anything useful.  Just a bunch of entries like this:

```
2018-08-09 22:04:54,202 INFO spawned: 'searchmaint' with pid 113
2018-08-09 22:04:54,749 INFO success: searchmaint entered RUNNING state, process has stayed up for &gt; than 0 seconds (startsecs)
2018-08-09 22:09:55,084 INFO exited: searchmaint (exit status 0; expected)
2018-08-09 22:09:56,087 INFO spawned: 'searchmaint' with pid 116
```

Happy to debug further.  Let me know what else I can try.

**Comment by grahamgilbert** [comment]
Look in /tmp in the container for the actual gunicorn logs.

**Comment by bfreezy** [comment]
Thanks.  So, I found the stack trace in sal.log

Namely - ``FieldError: Cannot resolve keyword 'installed' into field.``

Full error below:

```
[15/Aug/2018 19:28:19] ERROR [django.request:124] Internal Server Error: /list/Pending3rdPartyUpdates/MSOneNote2016--16.16.18081201/business_unit/1/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/docker/sal/server/views.py", line 89, in machine_list
    machines, title = plugin_object.filter_machines(queryset, data)
  File "/home/docker/sal/sal/plugin.py", line 329, in filter_machines
    machines, data = self.filter(machines, data)
  File "/home/docker/sal/server/plugins/pending3rdpartyupdates/pending3rdpartyupdates.py", line 37, in filter
    installed=False)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 794, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 812, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1227, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1253, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1133, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1019, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/query.py", line 1327, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
FieldError: Cannot resolve keyword 'installed' into field. Choices are: activity, broken_client, conditions, console_user, cpu_speed, cpu_type, deployed, errors, facts, first_checkin, hd_percent, hd_space, hd_total, historical_facts, hostname, id, installed_updates, inventory, inventoryitem, last_checkin, last_puppet_run, machine_group, machine_group_id, machine_model, machine_model_friendly, manifest, memory, memory_kb, munki_version, operating_system, os_family, pending_apple_updates, pending_updates, pluginscriptsubmission, profile, puppet_errors, puppet_version, report, sal_version, searchcache, serial, updatehistory, warnings
```

Not sure if this issue is just unique to me or an issue with a model elsewhere in the project?  I get this same stack trace on any objects that I click within the Pending3rd Party Updates table.

**Comment by grahamgilbert** [comment]
Take a look at https://github.com/salopensource/sal/pull/281 - this should fix the problem.

**Comment by bfreezy** [comment]
I applied #281 and it fixed the issue for me.  Thank you!
