### ISSUE TITLE
Preflight/Postflight errors

### ISSUE THREAD

**Issue by eshora** [salopensource/sal#294]
When running managedsoftwareupdate -vvv this machine will update via munki and download the correct packages and stay updated but when it comes to the Preflight/Postflight tasks and reporting back to Sal I get the following errors:

Starting...
    Performing preflight tasks...
    preflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/preflight.d/sal-preflight", line 174, in <module>
    all_prefs = get_prefs()
  File "/usr/local/munki/preflight.d/sal-preflight", line 44, in get_prefs
    required_prefs["key"] = utils.pref('key')
AttributeError: 'module' object has no attribute 'pref'

    Performing postflight tasks...
    postflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/postflight.d/sal-postflight", line 577, in <module>
    main()
  File "/usr/local/munki/postflight.d/sal-postflight", line 68, in main
    ServerURL, NameType, bu_key = get_server_prefs()
  File "/usr/local/munki/postflight.d/sal-postflight", line 120, in get_server_prefs
    required_prefs["key"] = utils.pref('key')
AttributeError: 'module' object has no attribute 'pref'
Done.

Any ideas on what the fix would be for this??

Thanks!

**Comment by grahamgilbert** [comment]
Looks like you didn't install the latest version of the package.   
  

  
  

  
  
>

**Comment by grahamgilbert** [comment]
Sal scripts.

**Comment by eshora** [comment]
After updating it to Sal Scripts 2.1.3 I get the following error now..

Starting...
    Performing preflight tasks...
    preflight return code: 1
    preflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/preflight", line 19, in <module>
    main()
  File "/usr/local/munki/preflight", line 15, in main
    utils.run_scripts(PREFLIGHT_DIR, sys.argv[1])
AttributeError: 'module' object has no attribute 'run_scripts'
    managedsoftwareupdate run aborted by preflight script: 1

**Comment by grahamgilbert** [comment]
I would remove everything the installer puts there and reinstall. It sounds like you are still missing something. Bin the launchdaemons, /usr/local/sal and the pre and post flight bits from Munk’s install directory.

**Comment by eshora** [comment]
Hey Graham,
Removed all that you mentioned above, updated sal scripts along with the latest sal update 3.3.11 and still having the same issue.  Any other suggestions?


```
Starting...
    Performing preflight tasks...
    preflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/preflight.d/sal-preflight", line 174, in <module>
    all_prefs = get_prefs()
  File "/usr/local/munki/preflight.d/sal-preflight", line 44, in get_prefs
    required_prefs["key"] = utils.pref('key')
AttributeError: 'module' object has no attribute 'pref'

    Performing postflight tasks...
    postflight stderr: Traceback (most recent call last):
  File "/usr/local/munki/postflight.d/sal-postflight", line 577, in <module>
    main()
  File "/usr/local/munki/postflight.d/sal-postflight", line 68, in main
    ServerURL, NameType, bu_key = get_server_prefs()
  File "/usr/local/munki/postflight.d/sal-postflight", line 120, in get_server_prefs
    required_prefs["key"] = utils.pref('key')
AttributeError: 'module' object has no attribute 'pref'
```

**Comment by grahamgilbert** [comment]
I'm going to say you didn't `rm` everything I suggested. `pref` is definitely in utils https://github.com/salopensource/sal-scripts/blob/master/payload/usr/local/sal/utils.py#L50

No changes have been made to `sal-scripts` since the last release.

**Comment by sheagcraig** [comment]
This could be a name clash with `utils` as discussed in Slack the other day.

There's an issue for that: https://github.com/salopensource/sal-scripts/issues/40


@eshora this is definitely an issue with sal-scripts, so feel free to jump in on that issue; closing this one.
