### ISSUE TITLE
Latest XProtect Version is not detected by default plugin

### ISSUE THREAD

**Issue by 1dustindavis** [salopensource/sal#317]
**Describe the bug**
The latest XProtect version shipped by Apple (`2102`) does not update `Version` in `/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/XProtect.meta.plist`.

The [current plugin](https://github.com/salopensource/sal/tree/master/server/plugins/xprotectversion) that ships with Sal uses that plist to determine the machines current XProtect Version, but an up-to-date machine with `2102` still returns `2101`.

You can check if a machine has `2102` by checking for the pkg receipt: `pkgutil --pkg-info com.apple.pkg.XProtectPlistConfigData.16U4051`. Sadly, that command is specific to each XProtect release, so it can not be used generically without additional processing.

**To Reproduce**
1. Confirm an enrolled machine has `2102` by running `pkgutil --pkg-info com.apple.pkg.XProtectPlistConfigData.16U4051`
2. Check the "XProtect" plugin on Sal's homepage
3. Only `2101.0` is displayed

**Expected behavior**
The plugin should display `2102` for all machines with `2102` installed.

**Server (please complete the following information):**
 - Host: docker
 - Version: 3.3.15.1632

**Client (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Safari
 - Version: 12.1

**Additional context**
The issue is fairly straight forward, but since Apple does not document XProtect, it is not clear if the issue will be resolved in a future XProtect version, or if this is the way it will be forever.

One potential solution would be to use the pkg receipt to determine the current version, but as I mentioned above, that will require additional logic to determine the latest version.

This bash one-liner ([stolen from Rich Trouton with slight modifications](https://derflounder.wordpress.com/2016/03/28/checking-xprotect-and-gatekeeper-update-status-on-macs/)) shows one method:
```bash
for i in $(pkgutil --pkgs=".*XProtect.*"); do pkgutil --pkg-info $i | awk '/version/ {print $2}'; done | sort -n | tail -1
2102.1.1555398512
```

**Comment by 1dustindavis** [comment]
At least on 10.14.4 with XProtect version `2102`, this command works:
```bash
defaults read /System/Library/CoreServices/XProtect.bundle/Contents/version.plist CFBundleShortVersionString
```

I can submit a PR, but I have no idea if this is reliable on older OS or XProtect versions. (Testing old XProtext versions sounds real annoying)

**Comment by grahamgilbert** [comment]
I'm fine with a split in the logic for 10.13 and 10.14. All we really need to know is if the old method works on 10.13. If so, I'm happy to make the assumption that the fruit co just changed it for 10.14.

**Comment by erikng** [comment]
Dustin, spin up an old OS without network access and run that command. If it works and is accurate I'd say there's a pretty high chance it will always work.

Good catch btw.

Thanks,
Erik Gomez
________________________________

**Comment by 1dustindavis** [comment]
A new XProtect version was released today and actually has the correct version number in `XProtect.meta.plist`, so I am closing this since it was likely just a one-time mistake on Apple's side.
