### ISSUE TITLE
More machines with errors than have apparently checked in

### ISSUE THREAD

**Issue by ewancolyer1** [salopensource/sal#334]
**Describe the bug**
On a newly set up instance of Sal v4 (a fresh install in kubernettes) on the dashboard it is reporting that I have 57 machines with warnings, but only 40 as being active.

**To Reproduce**
1. Set up a fresh instance of SAL
2. Get some machines to check in
3. See that more machines have errors that total machines have checked in :P (see below screenshot)

**Screenshots**
![image](https://user-images.githubusercontent.com/32178903/64621750-23e63280-d3de-11e9-85cb-a06a93c3c515.png)

**Server (please complete the following information):**
 - Kubernettes in GCP
 - Sal  v4 with sal_scripts v3.0.2

**Client (please complete the following information):**
 - OS: [e.g. macOS 10.14.1, iOS18, WindowsXP]
 - Browser [e.g. safari]
 - Version sal scripts v3.0.2

**Additional context**
This is the 1st time any of these clients have had sal installed on them, and the enviroment has **not** been migrated from sal v3 

No difference in behaviour when debug is turned on

**Comment by sheagcraig** [comment]
Hmmm... Also, not right!

**Comment by sheagcraig** [comment]
That's totally what's happening.
