### ISSUE TITLE
Multiple lines for same Pending app updates

### ISSUE THREAD

**Issue by pmamberti** [salopensource/sal#335]
**Describe the bug**
We see multiple entries with a count of 1 in the Pending Updates plugins, instead of one entry with the count of the machines. Could not find a similar one in the open issues

**To Reproduce**
1. In  the Business Unit view, look the _Pending 3rd Party updates_ and Pending Apple Updates_ plugins.

 **Expected Behavior**
Pending updates are displayed one each line, and the number at the end reflects the number of machines that need to install the update.

**Screenshots**
<img width="644" alt="Screenshot 2019-09-10 at 15 28 52" src="https://user-images.githubusercontent.com/22891384/64623274-99530280-d3e0-11e9-8801-2964d4c824cf.png">

**Server (please complete the following information):**
 - Docker 
 - sal v`4.0.2`

**Client (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser Chrome and Safari
 - Version 77 and 12.1.2

**Additional context**
n/a

**Comment by sheagcraig** [comment]
Yeah, that's not right.

**Comment by pmamberti** [comment]
Thanks! 🙌🏼
