### ISSUE TITLE
Current Django Rest Framework drops support for CoreAPI and docs site

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal#352]
**Is your feature request related to a problem? Please describe.**
Time moves on, and apparently, according to https://www.django-rest-framework.org/community/3.10-announcement/#continuing-to-use-coreapi openapi has emerged as the dominant standard over coreapi. As a result, the 3.10 DRF starts deprecating coreapi, and the builtin docs site is gone.

**Describe the solution you'd like**
I've updated some internal sites to use openapi to generate the schema, it was basically a one-liner in the urls file. Easy.

Then we need to decide whether we prefer the Swagger docs or the Redoc docs sites. Both, also, look to be very easy to swap in. I've tried the ReDoc site and it seems great. If anyone has strong opinions one way or the other, I'd love to hear them.

**Describe alternatives you've considered**
A docs site isn't entirely necessary; the API is already browse-able.

**Comment by grahamgilbert** [comment]
No strong opinions apart for I would rather it remains in python - I've see quite a few that are node based.

**Comment by sheagcraig** [comment]
I worked on this some today; the newer DRF requires you explicitly reference the schema generator you want to use, but they are claiming they're going to support the CoreAPI doc site for as long as possible, so I'm just going to leave it alone until it breaks.

It took me about 3 minutes of messing around to use redoc instead last time, so unless someone is really hot to get on swagger or redoc, I'm good.
