### ISSUE TITLE
When searching the Application Inventory, it spawns a query for every character typed

### ISSUE THREAD

**Issue by natewalck** [salopensource/sal#359]
**Describe the bug**
When you search a data table (such as the Application Inventory), it spawns a query for each character typed instead of waiting for typing to stop or a return (enter) to occur.

**To Reproduce**
1. Go to 'http://serverinventory/all/0/'
2. Click in the Search box in the top right
3. Start typing something to search for
4. Observe queries spinning up (debug mode helps). See: https://gist.github.com/natewalck/6d5060ba52244f4d8c9040000349f681

**Expected behavior**
It should either wait for you to finish typing (some amount of time while no typing is occuring) or wait for a specific action, like an Enter/Return.

**Server (please complete the following information):**
 - N/A
 - All versions

**Client (please complete the following information):**
 - macOS 10.15
 - Chrome
 - V78

**Comment by sheagcraig** [comment]
Datatables has a cooldown parameter which will wait Xms after input before updating which we can use here.

**Comment by sheagcraig** [comment]
Problem solved!
Inventory now waits until 3 characters have been typed in the search to spawn a query; and then it waits 1000ms before actually doing so, letting you type more realistically.

You can hit enter at any time to fire the query immediately.
