### ISSUE TITLE
Allow 'pinning' of specific sort columns, e.g. `Activity/1-hour` table

### ISSUE THREAD

**Issue by arubdesu** [salopensource/sal#36]
Currently computer groups are sorted by last checking for all tables views. For at least the `Activity/1-hour` view, I'd want it to always be sorted by computername. Some discussion in Slack hinted that this may be possible to implement, conditionally per-user or otherwise.

**Comment by grahamgilbert** [comment]
This has been implemented on the main views. Was merely ``stateSave: true`` to the datatable section. If there are any templates I've missed let me know.
