### ISSUE TITLE
Django Language code error on latest build

### ISSUE THREAD

**Issue by LemonArk** [salopensource/sal#375]
**Describe the bug**
Sal fails to load properly, looking at the debug logs, 

SystemCheckError: System check identified some issues:
 
 ERRORS:
 ?: (translation.E001) You have provided an invalid value for the LANGUAGE_CODE setting.

**To Reproduce**
Creating new sal container from macadmins/sal:latest

Using an older image, macadmins/sal:cleanup_plugin_code, does not appear to suffer the same bug

I checked a couple of spots I thought might have an issue, system_settings.py LANGUAGE_CODE seems to match between versions

I noticed an environment variable listed in the docker file and tried a few entries with 
-e DOCKER_SAL_LANG="some lang code here"

but no luck. 

First time setting up sal and not very adept at docker so many I am just doing something wrong here. 
 ¯\_(ツ)_/¯

**Comment by nathandarnell** [comment]
I changed the Dockerfile language to **en-us** and in settings_import.py both mentions of language to **LANGUAGE_CODE = 'en-us'** and it works.  I don't know why just changing it in the Dockerfile didn't fix it but it might be me.

**Comment by grahamgilbert** [comment]
This is the same problem as https://github.com/grahamgilbert/Crypt-Server/pull/87 I think.

**Comment by sheagcraig** [comment]
I see some commits in changing the language... Is this solved?

**Comment by gavinelder** [comment]
Raised https://github.com/salopensource/sal/pull/376 to resolve.
