### ISSUE TITLE
search_maintenance not working from cron as root

### ISSUE THREAD

**Issue by tpegues2** [salopensource/sal#406]
I'm trying to run search_maintenance from cron as root and it is failing.
Do I need to do be in the virtual env like below before I call search_maintenance?
The script is running as a root cron job.

--------------------------------------------------------------------------
#!/bin/bash
su - saluser
cd sal_env
source bin/activate
cd /usr/local/sal_install/sal
export PYTHONPATH=/usr/local/sal_install/sal:$PYTHONPATH
export DJANGO_SETTINGS_MODULE='sal.settings'
/usr/local/sal_install/sal_env/bin/python manage.py search_maintenance

**Comment by sheagcraig** [comment]
Failing how? Thanks for the script above! That's a good start.

**Comment by tpegues2** [comment]
Thank you!   Here is the warning that I get.  Does this means it failed?  
/srv/saluser/sal_env/lib/python3.6/site-packages/django/db/models/fields/__init__.py:1368: RuntimeWarning: DateTimeField SavedSearch.created received a naive datetime (2020-09-12 11:06:58.884382) while time zone support is active.
  RuntimeWarning)

**Comment by grahamgilbert** [comment]
This is not a failure, only a warning (although your python version is pretty old, but unrelated to this).
