### ISSUE TITLE
Timezone stuck on BST 

### ISSUE THREAD

**Issue by Fallout476** [salopensource/sal#423]
**Describe the bug**
using th TZ option in docker does not change the timezone from BST to local or UTC

the timezone is correct on the db

saldb1=# SHOW TIMEZONE;
      TimeZone
---------------------
 America/Los_Angeles
(1 row)

however, this is what is displayed on the front end.

<img width="187" alt="Screen Shot 2021-06-24 at 2 08 58 PM" src="https://user-images.githubusercontent.com/68404816/123311962-babda980-d4f5-11eb-9506-19dccb419e4a.png">

**Expected behavior**
when using the TZ option, the timezone changes to the timezone we desire.

**Server (please complete the following information):**
 - Host environment Docker running on Centos7, with an external postgres DB mounted
 - Version Sal 4.1.9, Sal Scripts 4.0 and 4.1.1

**Client (please complete the following information):**
 - OS: macOS 10.13,14,15 & 11

**Additional context**
Sal refuses to run nginx in DEBUG MODE 

from the log
sal-d.REDACTED docker[122675]: /bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)

**Comment by grahamgilbert** [comment]
I cannot replicate this. Please share your full docker run command, and if you are mounting in a custom settings.py, please share that as well.

**Comment by Fallout476** [comment]
/bin/docker run \
	--rm \
	--name=sal  \
	--hostname=sal \
	-p 443:443 -p 8000:8000 \
	-v /etc/letsencrypt/live/sal.<fqdn>/sal.conf:/etc/nginx/sites-enabled/sal.conf \
	-v /etc/letsencrypt/live/<sal.<fqdn>:/opt \
	-v /opt/docker/salprod/plugins:/home/docker/sal/plugins  \
	-e DB_HOST=<HOST>   \
	-e DB_PORT=<port> \
	-e ADMIN_PASS=<password> \
	-e DB_NAME=<db name> \
	-e DB_USER=<db user> \
	-e DB_PASS=<password> \
	macadmins/sal:4.1.9

**Comment by grahamgilbert** [comment]
> is the TZ var during the container startup?
I don't understand this question. If you aren't passing in the TZ setting, Django will use the timezone set on the server.

**Comment by vphan13** [comment]
That's what we thought too, TZ on the server is America/Los_Angelos, yet the web page shows BST.  There is no where in our environment where the TZ is BST, not the docker host, postgres server, or postgres DB itself

**Comment by machinas-achim** [comment]
Hello @vphan13  

Perhaps you can experiment with these environment variables, they work for us:

```
  -e TZ="Europe/Madrid" \
  -e DOCKER_SAL_TZ="Europe/Madrid" \
```
