### ISSUE TITLE
add pkg receipts to stored inventory per client

### ISSUE THREAD

**Issue by arubdesu** [salopensource/sal#43]
There are installs of binaries and such that don't show in sys_profiler's apps output, so we'd want to collect the receipts pkgutil knows about. Would be useful for example in cases like the apple receipt of the ethernet-driver-blacklisted-kext fiasco .

**Comment by grahamgilbert** [comment]
How do you propose these are stored? Collecting the information is relatively easy, but devising the right database structure to store it is another matter. 

Sent from my iPhone




On Sun, Feb 28, 2016 at 8:31 AM -0800, "Allister Banks" <notifications@github.com> wrote:












There are installs of binaries and such that don't show in sys_profiler's apps output, so we'd want to collect the receipts pkgutil knows about. Would be useful for example in cases like the apple receipt of the ethernet-driver-blacklisted-kext fiasco .

**Comment by arubdesu** [comment]
I'm only guessing that somewhere like https://github.com/salopensource/sal/blob/master/inventory/models.py would be appropriate to add a new  PkgReceiptItem, even though there's a lot of crossover, criteria-wise with the current InventoryItem? It would seem good to have them get mixed in with the apps display for now.

**Comment by grahamgilbert** [comment]
I would say this would be worth collaborating with @sheagcraig on this since he's working on a big rewrite of this.

**Comment by sheagcraig** [comment]
Yeah, hmmm. I guess there could be an optional field on the InventoryItem model for receipts. Or another table entirely for receipts. Have to think about this.

**Comment by arubdesu** [comment]
If I'm not mistaken we'll see items without receipts and vise versa, so it would almost certainly be a separate model

**Comment by arubdesu** [comment]
I'll let it close since I can't be an active user anytime soon 😿
