### ISSUE TITLE
DiskSpace plugin - 8% or 9% become 80% or 90% in dashboard

### ISSUE THREAD

**Issue by cristianmaida** [salopensource/sal#459]
**Describe the bug**
In DiskSpace plugin Mac with 8% of used disk are in warnign with 80% of used disk
MAc with 9% of used disk are in error with 90% of used disk

![Screenshot 2023-10-27 alle 11 34 27](https://github.com/salopensource/sal/assets/7722880/eb2aa332-9078-4a83-8036-776f4f2b03fa)

![Screenshot 2023-10-27 alle 11 34 57](https://github.com/salopensource/sal/assets/7722880/8d1985f7-7709-4900-ae09-c05c86dbfdf7)

**Comment by w0de** [comment]
I can't replicate this on latest. Edited device to match shown values as precisely as possible:

<img width="411" alt="Screenshot 2023-10-27 at 12 45 46 PM" src="https://github.com/salopensource/sal/assets/20032435/48b6714d-8449-48a2-a11c-a186b319c256">
<img width="475" alt="Screenshot 2023-10-27 at 12 45 30 PM" src="https://github.com/salopensource/sal/assets/20032435/d7366573-e910-4b0e-849f-35962aede7e0">

What Sal version are you using?
Is this reproducible with any device in your env, or specific to a subset?

**Comment by w0de** [comment]
Actually, this is occurring with one (recently wiped) device in our dev instance of Sal. It's notable that this instance is using psql - my local reproduction attempt above is using sqlite. 

Suspect this may have something to do with [cached querysets](https://docs.djangoproject.com/en/2.1/topics/db/queries/#caching-and-querysets).

**Comment by cristianmaida** [comment]
Latest version of SAL deployed with docker, also latest version of SAL Script.
Any Mac device in my env has this bug.

**Comment by grahamgilbert** [comment]
I have just spot checked about 10-15 devices and they're reporting accurately here. However, we are still on Sal version 4.1.9.

**Comment by ChefAustin** [comment]
Just came across a device in our production Sal deployment that erroneously fell into the _"Machines with more than 90% disk utilization"_ bucket:
![image](https://github.com/salopensource/sal/assets/24925402/780d040b-4e50-4dca-87f4-587bb80a5c80)

- Sal scripts v4.8.0
- Sal v4.1.11.2263 (Docker)
- Postgres v15.3 (AWS RDS)

**Comment by grahamgilbert** [comment]
I cannot replicate this. Y’all are going to have to do some digging with
Postgres and the Django shell to see if you can see where the error is.
