### ISSUE TITLE
facter3 uptime not reflected in plugin

### ISSUE THREAD

**Issue by arubdesu** [salopensource/sal#51]
`facter` is being called on [postflight](https://github.com/salopensource/sal-scripts/blob/master/sal-postflight#L272) with the `--puppet` and `yaml` options, which would only contain the new format by default.  The way we flattened facter output turns that into `system_uptime=>days`, which isn't what [the plugin](https://github.com/salopensource/sal/blob/master/server/plugins/uptime/uptime.py#L33-L35) can therefore pull out.
We could handle this by throwing a conditional in the plugin (I guess, but facter version isn't a top-level value in the machine model), dropping facter2 support and changing the [fact_name] that is checked, or add the --show-legacy option and put either of those above changes off for now.

**Comment by grahamgilbert** [comment]
I think this would be easiest to do in the plugin since we get `facterversion` as a fact.

**Comment by grahamgilbert** [comment]
Or just grab both values and add them together

**Comment by arubdesu** [comment]
I kindof just want to throw a conditional in the postflight during the hashrocketing to make sure we set an uptime_days key and leave the plugin as-is? Waddaya think:
``` python
def hashrocket_flatten_dict(input_dict):
    """Flattens the output from Facter 3"""

    result_dict = {}
    for fact_name, fact_value in input_dict.items():
        if type(fact_value) == dict:
            # Need to recurse at this point
            if 'days' in fact_value:
                result_dict['uptime_days'] = fact_value.get('days')
            # pylint: disable=line-too-long
            for new_key, new_value in hashrocket_flatten_dict(fact_value).items():
                result_dict['=>'.join([fact_name, new_key])] = new_value
```
OK to PR with that against the postflight repo?

**Comment by grahamgilbert** [comment]
I'm not seeing the benefit here rather than fixing it in the plugin?

**Comment by arubdesu** [comment]
Well for one thing, what I'm trying doesn't seem to fix it:
``` python
        try:
            ok = machines.filter(facts__fact_name='uptime_days', facts__fact_data__lte=1).count()
            ok += machines.filter(facts__fact_name='system_uptime=>days', facts__fact_data__lte=1).count()
            warning = machines.filter(facts__fact_name='uptime_days', facts__fact_data__range=[1,7]).count()
            warning += machines.filter(facts__fact_name='system_uptime=>uptime_days', facts__fact_data__range=[1,7]).count()
            alert = machines.filter(facts__fact_name='uptime_days', facts__fact_data__gt=7).count()
            alert += machines.filter(facts__fact_name='system_uptime=>uptime_days', facts__fact_data__gt=7).count()
        except:
```

**Comment by grahamgilbert** [comment]
Fixing this in the upcoming version with moving away from Facter to gather this data.

**Comment by grahamgilbert** [comment]
Fixed!
