### ISSUE TITLE
The "All Machines" view showing wrong time zone

### ISSUE THREAD

**Issue by efranklin** [salopensource/sal#52]
I've set the local timezone and the "Latest Run" shows the correct time unless you view "All Machines" globally or for a specific business unit. The machine record in the database also shows the correct time. 

Also, if searching for a machine, the table view shows the correct time under "Latest Run"

**Comment by grahamgilbert** [comment]
This is weird. The code to display those items is identical. How have you set the timezone?

**Comment by efranklin** [comment]
I set the timezone with this line:  -e DOCKER_SAL_TZ="America/Detroit"

**Comment by grahamgilbert** [comment]
Fixed!
