### ISSUE TITLE
Machine serial is modified, becomes issue when dealing with multiple inventory sources and VMs

### ISSUE THREAD

**Issue by headmin** [salopensource/sal#54]
https://github.com/salopensource/sal/blob/6588d820bff301e3c7ea349baf7cedec74817215/server/views.py#L1664-L1669

Uppercase and deleting characters results in SAL reporting a very different machine serial compared to munki, osquery, santa and other tools used in the community. In case one is aggregating multiple inventory sources a virtual machine synced  from SAL (via API) is very different - resulting in odd behaviour in systems like Zentral that people report to us.

The issue could be fixed on the client side by pretending an Apple like serial to VMware - but the above code looks like a short way to get things rolling from longer ago. In case you'll refactor code sometime in future I'd be more than happy if you'd consider using the reported serial 'as is' so it will match the ones reported by other tools.

**Comment by gregneagle** [comment]
/ and + can cause some "interesting" problems in a URL, though, no?

**Comment by grahamgilbert** [comment]
Yeah, this is basically impossible with slashes. I've never seen this in machines other than VMs and I can take it into account in Sal, Puppet and Munki. Unless you propose a good solution, I'm hesitant to change anything.

**Comment by headmin** [comment]
sure - it may be debatable modifying data for some sort of unique ID. no interest in starting long discussion on this thing - but there's of course ways to deal with it
