### ISSUE TITLE
Can not move Computer from one Business Group to another.

### ISSUE THREAD

**Issue by thomas-dam** [salopensource/sal#6]
delete com.salopensource.sal.plist from client
remove Computer from Business Group "A"
Write a com.salopensource.sal.plist with key from Business Group "B".

Expected result:

Computer should be member of Business Group "B" after submiting to Sal. 

Actual result:

Computer is still member of Business Group "A".

Make no difference if i add Machine serial manually in Sal.

**Comment by grahamgilbert** [comment]
Do you mean machine group? Keys haven't been associated with business units for a while. What version of Sal are you on? I've been doing exactly as you describe for quite some time time and it's worked as expected. 

Graham Gilbert

**Comment by thomas-dam** [comment]
Bad description - sorry. I do of course mean "Moving Mac from business group A / machine group 1 to business group B / machine group 1.
I delete computer from the old machine group and run this
```#!/bin/bash

#read old key to verify.
echo "Old key:"
defaults read /Library/Preferences/com.salopensource.sal.plist key

#delete old key
defaults delete /Library/Preferences/com.salopensource.sal.plist key

#write new key.
defaults write /Library/Preferences/com.salopensource.sal.plist key "w9iediz7bzsk3wvmz5gtcb6z0vyftfixkyzmblbiyjinh59uwo5gtww2bjrfdz067sgql2b3e0py1ddrqbwh2npinvqxawxdjdsxhoa6lpusgxoiix4l478xdzujyop4"

#read new key to verify
echo "New key:"
defaults read /Library/Preferences/com.salopensource.sal.plist key

#write serial number to make sure if is the one removed from Sal.
$serial ioreg -c IOPlatformExpertDevice -d 2 | awk -F\" '/IOPlatformSerialNumber/{print $(NF-1)}'
Echo $serial
```
I tried to turn debug on in '/usr/local/munki/postflight.d', but i am a bit clueless what to look for.

And i am current on Sal 2.0.3

Thanks

**Comment by grahamgilbert** [comment]
You can get debug output from

/usr/local/munki/postflight.d/sal-postflight --debug

**Comment by thomas-dam** [comment]
I got the debug on - just don't know what to look for. Can't give you gist now, but will when i learn to stay away from experimental releases and and how to rollback in Docker.

**Comment by grahamgilbert** [comment]
Check that the key being sent is the one you expect. No changes to this part of the code have been made for a couple of months now, and I definitely did this myself this week and it worked as expected. 

Graham Gilbert

**Comment by thomas-dam** [comment]
You can just close this one as the issue is gone after Sal 2.1.0
