### ISSUE TITLE
CSV export is slow

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal#65]
Inventory csv export on SQLite is very slow. Other csv exports are pretty slow.

@grahamgilbert and I talked about me doing a pass through this at some point in the future.

**Comment by grahamgilbert** [comment]
I've discovered streaminghttpresponse - I think this will be the answer to my prayers here since we are going to be pulling lots of data whatever we do.

**Comment by grahamgilbert** [comment]
I've pushed this change to the server app. Early indications look promising.

**Comment by grahamgilbert** [comment]
This made things so much quicker. We need to implement this on the inventory export.

**Comment by grahamgilbert** [comment]
@sheagcraig Did you get anywhere with implementing the same method used by the main app for exporting csv's in the inventory app?

**Comment by sheagcraig** [comment]
I rewrote all of the csv processing in the py3 branch to centralize csv output in the codebase. Now inventory and the other views all use the same function, and it uses StreamingHTTPResponse. It seems to work great so far.

**Comment by sheagcraig** [comment]
py3 branch is merged into the 4.0.0  branch. Closing unless we discover greater sadness.
