### ISSUE TITLE
Fix Machine.machine_model_friendly = None

### ISSUE THREAD

**Issue by sheagcraig** [salopensource/sal#66]
Getting the friendly name currently requires a request to Apple. Build a cached table or put in the database the machine_model to machine_model_friendly values and use that, only checking with Apple when required. Or we could just have a static list.

Also, contrive a way to either update missing friendly values on a regular basis (when certain views get Machines?) or during a migration (for the static table perhaps).

I'm planning on looking into this.

**Comment by grahamgilbert** [comment]
I've adjusted the function that gets the name to look for other machines with an existing model name first. I've also added a management task that is run when the docker container starts - as it is a management task, it can be scheduled by cron or whatever for bare metal installs.

https://github.com/salopensource/sal/commit/b28c94c2f29725cf217bfbfd3b5016e634f2071c
