### ISSUE TITLE
Search not working as expected

### ISSUE THREAD

**Issue by korylprince** [salopensource/sal#67]
It would be nice to search for machines by the Munki ClientIdentifier/Manifest. From my research it doesn't look like this is possible without getting into the database.

**Comment by thomas-dam** [comment]
Works fine from the search field?
<img width="503" alt="screen shot 2016-09-13 at 20 44 42" src="https://cloud.githubusercontent.com/assets/6230694/18486838/038725a0-79f3-11e6-9804-1f7c380ab4d5.png">

**Comment by korylprince** [comment]
I've done some digging in the code and I'm still trying to understand what is going on.

I several manifests, but the two I'm dealing with now are staff_default and staff_testing.

The problem is I'm searching the term "staff_testing" which should return only three machines (well, only three have that ClientIdentifier), but returns hundreds. So the search is finding the machines with the manifest "staff_testing", but it's also returning many more machines that don't have that manifest.

I'm not too familiar with watson, but it seems like it's not treating "staff_testing" as a single term.

The other thing I've noticed is that while the report, errors, and warnings fields are excluded from searching, the activity and install_log fields (which are quite large) are not excluded, so I'm wondering if those fields are clobbering my search.

I will keep digging, but any thoughts as to what is happening?

**Comment by grahamgilbert** [comment]
You're almost certainly right. I'm planning on completely overhauling search to let you be more specific with which fields you are searching for.

**Comment by grahamgilbert** [comment]
I've excluded those fields for now (along with a couple of others that just contain housekeeping data). Please try the django1.10 branch and see if that gives better results.

**Comment by korylprince** [comment]
I'm sorry it's taken so long for a response. I'm currently using the docker image macadmins/sal:latest which I believe is 3.0.0b2. The search is now working like I would expect, only returning machines that have the manifest I searched for.

Thanks for fixing this!
