### ISSUE TITLE
Back button in Application Inventory doesn't go back if pressed Next page. 

### ISSUE THREAD

**Issue by erikberglund** [salopensource/sal#72]
Here is what I do:
1. Click 'Application Inventory'
2. Click Next to go to the next page.
3. Click Back in the menu, which takes me to the previous page, not back in the navigation.
4. Click Back again, which takes me forward again to the page I was at.

After that Back only toggles between the two recent pages.

Sal version 2.7.0.671

**Comment by grahamgilbert** [comment]
Inventory has been completely rewritten in the django1.10 branch. Can you try that and see if you're still having the problem?

**Comment by grahamgilbert** [comment]
Closing this as it is probably fixed. Please reopen if not.
